### ISSUE TITLE
Better animation

### ISSUE THREAD

**Issue by LasaleFamine** [LasaleFamine/polymer-youtube-feed#1]
The component needs a better animation!

**Comment by ghost** [comment]
Which component needs some help?

**Comment by LasaleFamine** [comment]
The only component that refers to this repo :D 

Actually I need a better CSS animation to display the play button on hover. You can see the demo cloning the repo and running the server (after installing all dependencies). 
By the way I'm in the middle of a refactor to Polymer 3, so this is one of the thing I want to improve.

**Comment by ghost** [comment]
I am working on learning full stack so just poking around to see what I can help with!
